### ISSUE TITLE
Crash to home screen in autonomous op mode "Camera Test No. 1"

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/velocity-vortex#3]
After initializing the op mode, the entire app crashes. The robot controller screen displays the message "Unfortunately, FTC Robot Controller has stopped"

**Comment by DarkLordZach** [comment]
The Camera Test No. 1 op mode requires OpenCV be installed (it is) and the CameraTestActivity installed (it isnt) I figured it wouldn't be a good use of development resources to fix the error in this so I scrapped it but forgot to remove the op mode. Will remove next time.
